### ISSUE TITLE
Level Design: Premade maps or randomized spawning maps

### ISSUE THREAD

**Issue by PaulTheFat** [keithlau2015/Final-Year-Project_-MazeChallenger#3]
Should we use Premade maps or randomized spawning maps?

Pros: 

Premade maps - Steady performance for using less resource, Better game experience (Better map layout and design, player pathfinding)

Randomized Spawning maps - Saves development time, Unique experience every game (More replayability than premade maps) 

Cons:

Premade maps - Longer development time, poor replayability.

Randomized Spawning maps - Uncertainty in pathfinding, game performance and gameplay. Harder implementations for additional functions.

**Comment by keithlau2015** [comment]
我覺得可以用premade maps會比較好, 有關耐玩性可以多做幾個premade map來解決

**Comment by PaulTheFat** [comment]
Decided to choose randomized map design for shorter development time
